---
enable_ufw_firewall: true
reboot_box: false
disable_ipv6: false  # breaks nginx install
timezone: UTC

# apt packages
install_packages:
  - ntp
  - ufw
  - unzip

# Used in configs/sshd_config.j2
# The argument must be "yes", "prohibit-password", "without-password", "forced-commands-only", or "no".
permit_ssh_root_login: "prohibit-password"
sshd_port: 22
gateway_ports: "no"  # "no", "yes", or "clientspecified"

# Enable SSH tasks
update_sshd_config: false
